---
title: "Bootstrapping"
author: "Hidde van de Beek"
date: '2023-01-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tibble)
library(infer)
```

```{r}
seed <- 28
mean.iq <- 100
sd.iq <- 15
samplesize <- 300
populationsize <- 17000000
bootstrap.iterations <- 2000000
```


Population distribution
```{r}
set.seed(seed)
iq <- rnorm(populationsize, mean = mean.iq, sd = sd.iq)
ggplot(as.data.frame(iq), aes(x=iq)) + 
 geom_histogram(aes(y=after_stat(density)), colour="black", fill="white", bins = 100)+
 geom_density(alpha=.2, fill="#FF6666") 
```


```{r}
sample.iq <- as.data.frame(iq) %>%
  rep_slice_sample(n = samplesize, reps = 10)
sample.iq$replicate <- as.factor(sample.iq$replicate)
ggplot(sample.iq, aes(x = iq, fill = replicate)) +
  geom_density(alpha=.2) +
  labs(
    x = "iq", y = "Number of samples",
    title = "sample distributions of iq"
  )
```
```{r}
sample_means <- c()
for(i in 1:bootstrap.iterations){
  sample_distribution <- sample(iq, samplesize, replace=F)
  sample_means$mean[i] <- mean(sample_distribution)
  sample_means$median[i] <- median(sample_distribution)
}
sample_means <- as.data.frame(sample_means)
ggplot(as.data.frame(sample_means), aes(x=mean)) + 
 geom_histogram(aes(y=after_stat(density)), colour="black", fill="white", bins = 100)+
 geom_density(alpha=.2, fill="#FF6666") 
ggplot(as.data.frame(sample_means), aes(x=median)) + 
 geom_histogram(aes(y=after_stat(density)), colour="black", fill="white", bins = 100)+
 geom_density(alpha=.2, fill="#FF6666") 
```


```{r}
resample.iq <- c()

for (i in 1:4){
  sample.iq2 <-sample.iq %>%
    filter(replicate == i)
  count <- bootstrap.iterations*(i-1)
  for (j in 1:bootstrap.iterations){
    count2 <- count + j 
    sample.loop <- sample(sample.iq2$iq, samplesize, replace = T)
    resample.iq$mean[count2] <-  mean(sample.loop)
    resample.iq$median[count2] <-  median(sample.loop)
    resample.iq$sample[count2] <- i
  }
}
resample.iq <- as.data.frame(resample.iq)
resample.iq$sample <- as.factor(resample.iq$sample)

ggplot(resample.iq, aes(x = mean, fill = sample)) +
  geom_density(alpha=.2) +
  labs(
    x = "iq", y = "Number of samples",
    title = "sample distributions of iq (mean)"
  )

ggplot(resample.iq, aes(x = median, fill = sample)) +
  geom_density(alpha=.2) +
  labs(
    x = "iq", y = "Number of samples",
    title = "sample distributions of iq (median)"
  )
```


```{r}
sample.iq%>%
 group_by(replicate) %>%
  summarise(median = median(iq))
resample.iq%>%
 group_by(sample) %>%
  summarise(interval1 = quantile(median, 0.025),
            interval2 = quantile(median, 0.975))

resample.iq.1 <- resample.iq %>%
  filter (sample == 1)
hist(resample.iq.1$median, breaks = 200)
abline(v = c(96.23779, 100.8129), col = 3)
abline(v = 98.32161, col = 2)
```



